#!/bin/sh

# stolen from template file
if git rev-parse --verify HEAD
then
    against=HEAD
else
    # Initial commit: diff against an empty tree object
    against=4b825dc642cb6eb9a060e54bf8d69288fbee4904
fi

FILES=`git diff --cached --name-only --diff-filter=ACMR $against | grep \\\\.php`

if [ "$FILES" != "" ]
then
	echo "Running Code Sniffer..."
	phpcs -n -p $FILES
	if [ $? != 0 ]
	then
		echo "Fix the error before commit."
		exit 1
	fi
fi
 
exit $?